require 'rspec/core/rake_task'
require 'rubocop/rake_task'
require 'foodcritic'
require 'kitchen'
require 'mixlib/shellout'
require 'kitchen/rake_tasks'

IGNORED_CLASSES = ["RSpec::Core::ExampleGroup"]
DUMP_FILE = "rubydeps.dump"
DOT_FILE  = "rubydeps.dot"
SVG_FILE  = "rubydeps.svg"

task default: "rubydeps:svg"

file DUMP_FILE do
  sh "RUBYDEPS=y rspec"
end

file DOT_FILE => DUMP_FILE do
  ignore_regexp = IGNORED_CLASSES.join "|"
  sh "rubydeps --class-name-filter='^(?!#{ignore_regexp})'"
  dot = File.read(DOT_FILE)
  dot.gsub!("rankdir=LR", "rankdir=TB")
  # Unfortunately due to https://github.com/dcadenas/rubydeps/issues/4
  # we need to manually exclude some superfluous dependencies which
  # go in the wrong direction.
  dot.gsub!(/\\\n/, "")
  dot.gsub!(/^(?=\s+Object )/, "#")
  dot.gsub!(/^(?=\s+"Pacemaker::Resource::Meta" ->)/, "#")
  dot.gsub!(/^(?=\s+"Pacemaker::CIBObject" ->)/, "#")
  dot.gsub!(/^(?=\s+"Chef::Mixin::Pacemaker::StandardCIBObject" -> "(?!Pacemaker::CIBObject))/, "#")
  dot.gsub!(/^(?=\s+"Chef::Mixin::Pacemaker::RunnableResource" -> "(?!Pacemaker::CIBObject))/, "#")
  File.open(DOT_FILE, "w") { |f| f.write(dot) }
end

file SVG_FILE => DOT_FILE do
  sh "dot -Tsvg #{DOT_FILE} > #{SVG_FILE}"
end

namespace :rubydeps do
  desc "Clean rubydeps dump"
  task :clean do
    FileUtils.rm_f([DUMP_FILE])
  end

  desc "Regenerate #{DUMP_FILE}"
  task dump: DUMP_FILE

  desc "Regenerate #{DOT_FILE}"
  task dot: DOT_FILE

  desc "Regenerate #{SVG_FILE}"
  task svg: SVG_FILE
end

# Style tests. Rubocop and Foodcritic
namespace :style do
  desc "Run RuboCop style and lint checks"
  RuboCop::RakeTask.new(:rubocop) do |t|
    t.options = ["-D"]
  end

  desc "Run Foodcritic lint checks"
  FoodCritic::Rake::LintTask.new(:foodcritic) do |t|
    t.options = { :fail_tags => ["any"] }
  end
end

desc "Run all style tests"
task :style => ['style:rubocop', 'sytle:foodcritic']

# Integration tests. Kitchen.ci
namespace :integration do
  desc 'Run test-kitchen pre-processing scripts'
  task :pre_cmds do
    cmd = Mixlib::ShellOut.new('./scripts/write_vagrantfile.rb')
    cmd.run_command
  end

  desc 'Setup the test-kitchen vagrant instances'
  task :vagrant_setup do
    Kitchen.logger = Kitchen.default_file_logger
    Kitchen::Config.new.instances.each do |instance|
      # this happens serially because virualbox/vagrant can't handle
      # parallel vm creation
      instance.create()

      # Initial converge
      instance.converge()

      # Then the second converge to enable the pacemaker resource agents
      instance.converge()
    end
  end

  desc 'Verify the test-kitchen vagrant instances'
  task :vagrant_verify do
    Kitchen.logger = Kitchen.default_file_logger
    Kitchen::Config.new.instances.each do |instance|
      # Run the integration tests now
      instance.verify()
    end
  end
end

# Clean up
namespace :cleanup do
  desc 'Destroy test-kitchen instances'
  task :kitchen_destroy do
    destroy = Kitchen::RakeTasks.new do |obj|
      def obj.destroy
        config.instances.each(&:destroy)
      end
    end
    destroy.destroy
  end

  desc 'Remove vagrant disks'
  task :rm_vdi do
    ::FileUtils.rm_rf('./vagrant_disks')
  end

  desc 'Remove Vagrantfiles/ dir'
  task :rm_vagrantfiles do
    ::FileUtils.rm_rf('./Vagrantfiles')
  end

  desc 'Remove .kitchen.local.yml'
  task :rm_kitchen_local do
    ::File.unlink('.kitchen.local.yml') if ::File.exist?('.kitchen.local.yml')
  end
end

desc 'Generate the setup'
task setup: ['integration:pre_cmds']

desc 'Clean up generated files'
task cleanup: ['cleanup:kitchen_destroy', 'cleanup:rm_vdi',
                 'cleanup:rm_kitchen_local', 'cleanup:rm_vagrantfiles']

desc 'Run full integration'
task integration: ['integration:pre_cmds', 'integration:vagrant_setup', 'integration:vagrant_verify']

# Default
task default: ['style', 'spec', 'integration']
