require_relative "pacemaker/resource/primitive"
require_relative "pacemaker/resource/clone"
require_relative "pacemaker/resource/ms"
require_relative "pacemaker/resource/group"
require_relative "pacemaker/transaction"
require_relative "pacemaker/constraint/colocation"
require_relative "pacemaker/constraint/location"
require_relative "pacemaker/constraint/order"
